name: NPM publish action
description: |
  Publishes NPM packages using the `npm` CLI.
inputs:
  version:
    description: The version bump type. Either "major", "minor" or "patch".
    required: true
  prerelease:
    description: Whether to publish as prerelease.
    required: false
    default: "false"
  dist-tags:
    description: The CSV list of dist tags to apply to release, if any. NPM defaults to if you don't provide any.
    required: false
    default: "latest"
  dry-run:
    description: Whether to run dry.
    required: false
    default: "false"
outputs:
  package-name:
    description: |
      The name of the processed package.
      
      Example: @infra-blocks/checks
  version:
    description: |
      The version of the released package, or would be released version in dry-run.
      
      Example: 1.2.3
  dist-tags:
    description: |
      The list of dist tags applied to the released package, as a JSON array.
      This output is available in dry-run too, even though no packages have been released.
      
      Example: [latest, git-sha-12345]
  git-tag:
    description: |
      The git tag applied to the commit, if any. This output is an empty when running in prerelease mode.
      It is available in dry-run too, even though no actual git tagging might have happened (prerelease false).
      
      Example: v1.2.3
  links:
    description: |
      A list of markdown links to the released package's registry versions of the form:
      [
        "[<package-identifier>](<version-registry-url>)"
      ]
      This output always: ["[<package>@dry-run](<latest-registry-url>)"] in dry-run.

runs:
  using: "docker"
  image: Dockerfile
  args:
    - ${{ inputs.version }}
    - ${{ inputs.prerelease }}
    - ${{ inputs.dist-tags }}
    - ${{ inputs.dry-run }}
