name: Git tag and publish

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  git-tag-semver-from-label:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: infrastructure-blocks/git-tag-semver-from-label-action@v1
