name: Self Test

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: self-test
        with:
          version: major
          prerelease: true
          dry-run: true
      - run: |
          echo "Released version: ${{ steps.self-test.outputs.released }} with dist-tags ${{ steps.self-test.outputs.dist-tags }}"
